"use client";\nimport Link from 'next/link';\nexport default function Footer() {\n    return (\n        <footer className="bg-[#2d4143] py-6 sm:py-8 mt-8 sm:mt-16">\n            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">\n                <div className="flex flex-col sm:flex-row justify-between items-center gap-6">
                    {/* Monash x Mosaic Logo */}\n                    <Link href="https://mosaic-ai-for-social-imp-5uoq4jm.gamma.site" target="_blank" rel="noopener noreferrer">\n                        <div className="w-[200px] h-12 sm:w-[280px] sm:h-[67px] md:w-[320px] md:h-[76px]">\n                            <img \n                                src="/assets/monash-mosaic-logo.png" \n                                alt="Monash x Mosaic" \n                                className="w-full h-full object-contain"\n                            />\n                        </div>\n                    </Link>\n\n                    {/* Social Icons */}\n                    <div className="flex items-center gap-4 sm:gap-6 md:gap-8">\n                        {/* Email */}\n                        <a \n                            href="mailto:contact@mosaic.monash" \n                            className="w-8 h-7 sm:w-10 sm:h-8 md:w-[47px] md:h-[38px] hover:opacity-80 transition-opacity"\n                            aria-label="Email"\n                        >\n                            <img \n                                src="/assets/email-icon.png" \n                                alt="Email" \n                                className="w-full h-full object-contain"\n                            />\n                        </a>\n\n                        {/* Instagram */}\n                        <a \n                            href="https://www.instagram.com/mosaic.monash/" \n                            target="_blank" \n                            rel="noopener noreferrer"\n                            className="w-8 h-8 sm:w-9 sm:h-9 md:w-[45px] md:h-11 hover:opacity-80 transition-opacity"\n                            aria-label="Instagram"\n                        >\n                            <img \n                                src="/assets/instagram-icon.png" \n                                alt="Instagram" \n                                className="w-full h-full object-contain"\n                            />\n                        </a>\n\n                        {/* LinkedIn */}\n                        <a \n                            href="https://www.linkedin.com/company/mosaic-monash-student-team/" \n                            target="_blank" \n                            rel="noopener noreferrer"\n                            className="w-8 h-8 sm:w-9 sm:h-9 md:w-11 md:h-11 hover:opacity-80 transition-opacity"\n                            aria-label="LinkedIn"\n                        >\n                            <img \n                                src="/assets/linkedin-icon.png" \n                                alt="LinkedIn" \n                                className="w-full h-full object-contain"\n                            />\n                        </a>\n                    </div>
                </div>
                <div className="mt-6 border-t border-[#ffffef]/30 pt-5 text-center sm:text-left">
                    <Link
                        href="/privacy-policy"
                        className="font-['Play'] font-bold text-[#ffffef] underline decoration-2 underline-offset-4 hover:text-[#ffb193] focus-visible:rounded-sm focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#ffffef]"
                    >
                        Privacy Policy
                    </Link>
                </div>
            </div>
        </footer>
    );\n}\n